version: 2.1
orbs:
  node: circleci/node@4.7.0
  #for bcrypt 
  python: circleci/python@1.4.0
  aws-cli: circleci/aws-cli@1.3.1
  #used this reference https://circleci.com/developer/orbs/orb/circleci/aws-elastic-beanstalk#jobs-deploy
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - checkout:
          path: ~/udagram
      - run:
          name: node-gyp install
          command: |
            npm i -g node-gyp
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy API
          command: |
            npm run backend:deploy
