version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.3.1
  #used this reference https://circleci.com/developer/orbs/orb/circleci/aws-elastic-beanstalk#jobs-deploy
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - node/install-packages:
          app-dir: udagram-backend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy API
          command: |
            npm run backend:deploy
